name: "Clevyrnetes Helm Deploy Action"
description: "Updates a Clevyrnetes Helm Chart"
branding:
  icon: upload-cloud
  color: green
runs:
  using: composite
  steps:
    - uses: frenck/action-setup-yq@v1
    - uses: mdgreenwald/mozilla-sops-action@v1.4.1
    - uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ env.GCLOUD_KEY_FILE }}
    - uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.GCLOUD_CLUSTER_NAME || 'clevyrnetes' }}
        project_id: ${{ env.HOST_PROJECT || 'momma-motus' }}
        location: us-central1
    - shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
      run: "$ACTION_PATH/main.sh"
