name: "Clevyrnetes Helm Deploy Action"
description: "Updates a Clevyrnetes Helm Chart"
branding:
  icon: upload-cloud
  color: green
runs:
  using: composite
  steps:
    - uses: frenck/action-setup-yq@v1
    - uses: mdgreenwald/mozilla-sops-action@v1.4.1
    - shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
      run: "$ACTION_PATH/main.sh"
