name: "Clevyrnetes Helm Deploy Action"
description: "Updates a Clevyrnetes Helm Chart"
branding:
  icon: upload-cloud
  color: green
runs:
  using: composite
  steps:
    - name: GCloud auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ env.GCLOUD_KEY_FILE }}
    - name: GKE auth
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GCLOUD_CLUSTER_NAME || 'clevyrnetes' }}
        project_id: ${{ env.HOST_PROJECT || 'momma-motus' }}
        location: ${{ env.GKE_LOCATION || 'us-central1' }}

    - name: Install Helm v3.12.3
      shell: bash
      run: |
        curl -sf https://get.helm.sh/helm-v3.12.3-linux-amd64.tar.gz | \
          tar -xzvf - --strip-components=1 \
          linux-amd64/helm
        mv helm "$(which helm)"

    - name: Set up SOPS
      uses: mdgreenwald/mozilla-sops-action@v1.5.0
    - name: Set up Helm secrets
      shell: bash
      run: helm plugin install https://github.com/jkroepke/helm-secrets --version=v4.5.1
    - name: Add Helm repo
      shell: bash
      run: |
        helm repo add clevyr "${HELM_URL:-https://helm.clevyr.cloud}"
        helm repo update clevyr

    - name: Main script
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
      run: "$ACTION_PATH/main.sh"
