name: "Clevyrnetes Helm Deploy Action"
description: "Updates a Clevyrnetes Helm Chart"
branding:
  icon: upload-cloud
  color: green
runs:
  using: composite
  steps:
    - shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
      run: "$ACTION_PATH/main.sh"
